# Spring Configuration
spring:
  application:
    name: "service-reservation-system"
    main:
      web-application-type: reactive
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  r2dbc:
    url: "r2dbc:postgresql://postgres-db:5432/dbtest"
    username: "postgres"
    password: "postgres"

  flyway:
    url: "jdbc:postgresql://postgres-db:5432/dbtest"
    user: "postgres"
    password: "postgres"
    locations: classpath:db/migration

  thymeleaf:
    reactive:
      enabled: true
      cache: false
      prefix: classpath:/templates/
      suffix: .html
      mode: HTML5

# SpringDoc Configuration - OpenAPI 3.0 Documentation & Swagger UI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method

# Spring Logging Configuration
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    com.srs: INFO

# Server Configuration
server:
  port: 8080

# JWT Configuration
jwt:
  secret:
    key: 586E3272357538782F413F4428472B4B6250655368566B597033733676397924