# Spring Configuration
spring:
  application:
    name: "service-reservation-system"
    main:
      web-application-type: reactive

  r2dbc:
    url: "r2dbc:postgresql://localhost:5433/it_db"
    username: "postgres"
    password: "postgres"

  flyway:
    url: "jdbc:postgresql://localhost:5433/it_db"
    locations: classpath:db/migration

  thymeleaf:
    reactive:
      enabled: true

  h2:
    console:
      enabled: true
      path: /h2-console

# SpringDoc Configuration - OpenAPI 3.0 Documentation & Swagger UI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method

# Server Configuration
server:
  port: 8080
